Update code_quality(python).yml

diff --git a/.github/workflows/code_quality(python).yml b/.github/workflows/code_quality(python).yml
--- a/.github/workflows/code_quality(python).yml
+++ b/.github/workflows/code_quality(python).yml
@@ -39,7 +39,7 @@ jobs:
       - name: Run Pylint and Generate Report
         run: |
           # Run pylint and save the output in a text file
-          pylint . > pylint-report.txt || true
+          pylint . > pylint-report.txt || echo "Pylint run failed" >> pylint-report.txt
 
       - name: Calculate Quality Score
         run: |
@@ -54,10 +54,15 @@ jobs:
           conventions=$(grep -oP 'C\d{4}' pylint-report.txt | wc -l || echo 0)  # Count 'C' errors (conventions)
 
           # Calculate LLOC as the sum of errors, warnings, and conventions
-          lloc=$((errors + warnings+conventions ))
+          lloc=$((errors + warnings + conventions))
 
-          # Calculate the quality score using the formula
-          quality_score=$(echo "scale=2; 10- ((5 * $errors + $warnings +$conventions) / $lloc) * 10" | bc)
+          # Prevent division by zero
+          if [ "$lloc" -eq 0 ]; then
+            quality_score="100"
+          else
+            # Calculate the quality score using the formula
+            quality_score=$(echo "scale=2; 10 - ((5 * $errors + $warnings + $conventions) / $lloc) * 10" | bc)
+          fi
 
           # Save the quality score to a file
           echo "Code Quality Score: $quality_score%" > quality_score.txt
@@ -96,3 +101,24 @@ jobs:
 
           # Push the changes to GitHub Pages
           git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} main --force
+
+      - name: Call API to Insert Quality Score
+        run: |
+         API_URL="https://dolphin-app-uzion.ondigitalocean.app/api/setQuality?clientpublic=baef7468287a44d8ac3634026d9fb8d1&clientsecret=181a2f3171117c1bd164c88b1171c1b83114fc1712121b12"
+         USER_ID="Akasi.co"
+         CLIENT_PUBLIC="baef7468287a44d8ac3634026d9fb8d1"
+         CLIENT_SECRET="181a2f3171117c1bd164c88b1171c1b83114fc1712121b12"
+         LAST_REQUEST_TIME="1733275263647"
+         projectid="Python1080"
+
+         curl -X POST "$API_URL" \
+           -H "Content-Type: application/json" \
+           -d "{
+              \"userid\": \"$USER_ID\",
+              \"clientpublic\": \"$CLIENT_PUBLIC\",
+              \"clientsecret\": \"$CLIENT_SECRET\",
+              \"projectid\": \"$projectid\",
+              \"recordtime\": \"$LAST_REQUEST_TIME\",
+              \"quality\": \"$quality_score\",
+              \"coverage\": \"$quality_score\"
+            }"
